name: "Build"

on: [ push, pull_request ]

jobs:
  job:
    name: "${{ matrix.os_label }}, ${{ matrix.cc }}, ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [ ubuntu-clang, ubuntu-gcc ]
        include:
          - name: ubuntu-clang
            os: ubuntu-latest
            os_label: Ubuntu
            cxx: clang++
            cc: clang

          - name: ubuntu-gcc
            os: ubuntu-latest
            os_label: Ubuntu
            cxx: g++
            cc: gcc

        build_type: [ Release, Debug ]

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install cmake"
        uses: lukka/get-cmake@latest

      - name: "Configure"
        run: |
          cd build
          cmake ..
          make
